language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- pytest
- python setup.py sdist
deploy:
  provider: releases
  api_key:
    secure: dg22gu+CuuMn6xTU1+7+ciFAHZ4896FTcGZizcMvCTUYyjAObtuzTwJAD+oL/ZnHUW7Gx0Y+9RIyz7bDCuUtpIFdNn37aZdo1PLnq5sYn5CvUmjHn8Qk85LNkWUbTtsM1B2dQWAYaYsdW/NZ+N+vQ9aDpSI8qCmB4yThgCpMJ8S4pFd2J8IPqx9rUZW4VR9kvpQ3oAra6TvH3xTh+emMjMLhZo322rqfT1+a7bxsIXE2MVL4J1lhWWTsiSRCEXOW11GMS9hhz5pnainHvCc8g7EvJ8Wq8WJxKtpo62da208pOGuHQkYLZiAJKH9Zmv/rXMclN3NMGOZShO6ZSoz171DS/caWpo7fC9TgCc4NF1kez/POYyvCBeEqBg4IPgH4fnYaMS1Bdn840QAXYLTxrmwpQzL7YU6ynRHvwdat7uxhYotj0E6ssy4ZavI/BSOqv4ubG1qZDgKDhBkSThe0Bc6YFdsziH/hDbsvIPhDOgSHk4svvsS8iXVv+MpDp+s41CPSmWcJ9ASpXcXzJIz2HqCWSsBEG99hlVQ7FfumhSmY0wOBAIcqUeXKV5CPSbgbkGbbuS2yUNvNgMmq2Cwu4gWsPEY7UaNIDgoT7uxGb0DWpB/3XgsqPZ7j+8NCJY5z4M3P7J8DfxN07B+6lcG4XuYZooUK2xoW9H0/Hip8Ya8=
  file: "dist/jmms.calculadora-0.0.3.tar.gz"
  on:
    repo: jmm-travis-org/python-travis-test
